### ISSUE TITLE
Lag every few seconds like BrianV1981 reported

### ISSUE THREAD

**Issue by Kasper9683** [Ppgtjmad/SimpleShops#61] opened 2020-09-29 05:50 UTC
I am encountering the same bug as  BrianV1981, I am experiencing "lag" spikes every few seconds when using SimpleShops. 
To stop this I remove simple shops from my mission.

**Comment by Kasper9683** [comment] 2020-09-29 05:54
After increasing and decreasing cleanup time, the problem still persisted.

**Comment by Kasper9683** [comment] 2020-09-29 06:01
After more experimenting, the issue persists even in an empty mission with SimpleShops. The best way to describe the problem is a freeze that lasts around a second which reoccurs every few seconds.

**Comment by Ppgtjmad** [comment] 2020-09-29 19:09
@Kasper9683 
Thanks for reporting, can you open the debug console while in editor and run this:

```
arr = [];
arr pushBack diag_activeSQFScripts; 
arr pushBack diag_activeScripts;
copyToClipboard str arr;
```

Then Ctrl+V the result here, thank you.

**Comment by Kasper9683** [comment] 2020-09-29 20:18
[[["APS_Anims\bootstrap\init_all.sqf","APS_Anims\bootstrap\init_all.sqf",true,23],["<spawn>
for ""_x"" from 1 to 4 do {
endLoadingScreen;
sleep 3;
};
","\gge_core\functions\fn_fixSplashScreen.sqf [gge_core_fnc_fixSplashScreen]",true,4],["<spawn>

_csys_uuniform = '';
_csys_usurf = '';

while {true} do
{
_csys_uuniform_upd = uniform _this;
_csy","real_camosystem\real_camosystem.sqf",true,1396],["<spawn>#line 1 ""C:\Users\n_rd2\Documents\Arma 3\mpmissions\SimpleShops.Altis\HG\Functions\Server\fn_cleanup","C:\Users\n_rd2\Documents\Arma 3\mpmissions\SimpleShops.Altis\HG\Functions\Server\fn_cleanup.sqf",true,48],["HG_fnc_paycheck","HG\Functions\Client\Generic\fn_paycheck.sqf [HG_fnc_paycheck]",true,10],["fn_animalBehaviour_mainLoop","A3\functions_f\ambient\fn_animalBehaviour.sqf [BIS_fnc_animalBehaviour]",true,231],["fn_animalBehaviour_mainLoop","A3\functions_f\ambient\fn_animalBehaviour.sqf [BIS_fnc_animalBehaviour]",true,349],["BIS_fnc_debugConsoleExec","A3\functions_f\Debug\fn_debugConsoleExec.sqf [BIS_fnc_debugConsoleExec]",true,25],["<spawn>
	private _fnc_scriptNameParent = if (isNil '_fnc_scriptName') then {'BW_WMO_fnc_leave'} else {_fnc_","",true,1]],[8,1,0,1]]

**Comment by Kasper9683** [comment] 2020-09-29 20:21
That's what was produced when using the mission that comes with simple shops (I only renamed it). Thank you for the fast response I appreciate it, hopefully we can narrow down the issue and resolve it.

**Comment by Ppgtjmad** [comment] 2020-09-30 15:55
Comment line 90 in HG\Setup\fn_serverInitialization.sqf that reads

`HG_CLEANUP_THREAD = [] spawn HG_fnc_cleanup;`

Check if the lag's gone. Report Back.

**Comment by Kasper9683** [comment] 2020-09-30 19:20
Removing the line that reads 

HG_CLEANUP_THREAD = [] spawn HG_fnc_cleanup; 

Fixed my issue entirely, Cheers!

**Comment by Ppgtjmad** [comment] 2020-10-03 22:48
e3dd1219ef8bd249e6895aeface30cc3515e343e should fix the issue while keeping the cleanup active.

**Comment by Ppgtjmad** [comment] 2020-10-05 18:33
Got enough feedback to know that the issue is fixed, closing.

**Closed by Ppgtjmad** 2020-10-05 18:33 UTC
