### ISSUE TITLE
Lag spikes after last update

### ISSUE THREAD

**Issue by BrianV1981** [Ppgtjmad/SimpleShops#59] opened 2020-09-11 02:56 UTC
Hello,
I am experiencing lag spikes every second or so ever since this last update. Prior to this update, I didn't experience any issues like this.

Regards,
Brian

**Comment by Ppgtjmad** [comment] 2020-09-15 12:25
@BrianV1981 

I have not noticed any lag spikes since the last update, make sure the cleanup time is not set too low (< 1 min).
Check your RPTs for clues. Report back.

**Comment by Ppgtjmad** [comment] 2020-09-28 13:25
No feedback from user, closing.

**Comment by Ppgtjmad** [comment] 2020-10-03 22:53
e3dd121 should fix the issue while keeping the cleanup active.

**Comment by Ppgtjmad** [comment] 2020-10-05 18:34
Got enough feedback to know that the issue is fixed, closing.

**Closed** 2020-10-05 18:34 UTC
Labels: bug, help wanted, question
