### ISSUE TITLE
Money not working

### ISSUE THREAD

**Issue by SLIgaming** [Ppgtjmad/SimpleShops#13] opened 2017-04-21 23:35 UTC
Editor pic
![20170422073245_1](https://cloud.githubusercontent.com/assets/27853081/25299095/33c5ca94-272e-11e7-9536-393fc368c7e2.jpg)

**Comment by Ppgtjmad** [comment] 2017-04-22 12:04
Hello,

I think it's fixed now https://github.com/Ppgtjmad/SimpleShops/commit/f4305027d72a77c436a998d138d5fe56a7e884b3

Can you try and report back here please?

**Comment by SLIgaming** [comment] 2017-04-22 23:15
Yup money is working now(Paychecks and kill reward). But TeamKillPenalty still count as a kill reward. I'll Look after a sleep but do you call with.
 if (side _killer == side player) then{YOUR CODE}; ?

**Comment by SLIgaming** [comment] 2017-04-22 23:18
Also where do you find the file where they edit the cash from? or are you on about the un pbo put into editor the repack ? Do you know much about mySQL or heard of Arma2NET ? Be nice and reliable to have this in a database ;)

**Comment by Ppgtjmad** [comment] 2017-04-23 01:16
I think you didn't get the point, I had it saving in client profileNamespace first. What I called "hacking" (notice the quotes) can be resumed to this:
- Random guy tries the shops in editor
- Random guy buys full gear & gives himself 1M cash
- Money & gear is saved in his profile
- Random guy connects to a server that uses the shops
- Server still uses old saving system (client profile)
- Money & gear is taken from client profile save
- Random guy is happy :)

Now everything is saved in server profile so the problem is solved.

I'm more than aware that using DB extensions is the way to go (using extDB3 in my framework) BUT I won't provide support, you have to do it yourself.

Plus don't forget that it's called simple shops, it has to stay simple so straighforward.

**Comment by SLIgaming** [comment] 2017-04-23 07:21
Ahhh I see now. I was a little confused at the profileNamespace. Awesome mate great work !

**Closed** 2017-04-23 11:01 UTC
