### ISSUE TITLE
Killing friendly (human) players gives reward instead of penalty

### ISSUE THREAD

**Issue by Asmodeuz** [Ppgtjmad/SimpleShops#1] opened 2017-03-05 07:26 UTC
Hey there,

it's Asmodeuz from Bistudio forums. Thank You once more for this awesome shop concept!

After you told that there was a new version available I took it for a test drive with a friend of mine on a dedicated server environment.

There a couple of issues emerged of which this is the first one. The other one needs an additional test just to confirm that the problem didn't arise from the fact that we were testing the mission on a dedicated server.

**Killing friendly (human) players gives reward instead of penalty**

So just to get to test the "Shops" and kill rewards asap I took your example mission, added three additional *playable* soldiers and two BIS player respawns (modules) and then exported it to multiplayer missions aaand finally transferred it to the dedicated server.

Then we two human players engaged in a shoot-each-other-just-to-test-things and noticed that when playing on the same side (whether it was OPFOR or BLUFOR didn't matter) **teamkills actually gave a reward instead of assessing a penalty**.

Not necessarily understanding what is going on in the scripts deep down I still take a stab at it just to throw ideas around:
would this behaviour be because of the default functionality gives reward for killing human players and in this case be it friendly or foe a human player is still a *human* player.

**Comment by Ppgtjmad** [comment] 2017-03-05 12:49
Hello,

Yeah sorry it's just a mistake with player side checking, should be fixed now :)

Thanks for the report.

**Comment by Asmodeuz** [comment] 2017-03-05 20:10
We ran tests with the changes you had made and I can confirm that it now works somewhat as intended (players get penalty for teamkills).

Here's the *somewhat*: there seems to be a small(ish) caveat most probably because of how the game handles friendly fire.

As we were testing we noticed a pattern where the player that continued to kill the same friendly player over and over again began getting rewards for the kills after the **first two teamkills** and continued to get rewarded so long until he either respawned or the other player killed this (serial)killer.

We reasoned that this could be because of how the game itself handles friendly fire. In case you have noticed when killing friendly AI in any mission where there happens to be friendly AI that they tend to turn against the player usually after the first two or so teamkills.
It would seem that after the two TK's the killer turns "hostile" against friendly players and is because of this considered as an enemy. Thus with the current form of your script teamkiller ends up getting rewards instead of getting the rightfull penalty.

Would you think there is something that could be done on your side or is this a thing that has to be lived with?

**Comment by Ppgtjmad** [comment] 2017-03-05 21:58
I think the problem is the entity rating that shifts player side when rating is low 

See description -> https://community.bistudio.com/wiki/addRating

I'll have to think of a proper way (if there is any) to do this. Will keep ya updated.

**Comment by Ppgtjmad** [comment] 2017-03-07 12:40
Ok I think I found something, so knowing that

> Each hit in a single player game will affect the player's rating. If it goes below -2000, he will be considered an enemy, and be attacked by all units.

> When the rating gets below -2000, the unit's side switches to "ENEMY" (sideEnemy) and the unit is attacked by everyone.

I just added a **HandleRating** EVH, so when it's <= 0 then rating will be set to 0 (PRIVATE) avoiding side switching.

Report back here when you can.

**Comment by Asmodeuz** [comment] 2017-03-07 17:24
We just tested with the addition you had made and killing friendly human players doesn't provide rewards anymore. Doing so only assesses the amount of penalty that has been set in _tkPenalty_ over and over again.

Consider this one fixed.

**Closed** 2017-03-07 18:49 UTC
