### ISSUE TITLE
XP/Money/Kill reward not working

### ISSUE THREAD

**Issue by Pamyux3** [Ppgtjmad/SimpleShops#70] opened 2022-04-02 14:36 UTC
Hiya and thank you for this amazing addon.

I am working on my mission file (MP) with a test AI (east side) spawned manually from the editor that i kill for testing.
I do not receive XP, kill or money when i kill the AI, why ?

I have check the config and it is set to TRUE also paycheck works and refresh the HUD normally.

Do i have to spawn the ai with specific params ?

Thanks,

**Comment by Ppgtjmad** [comment] 2022-04-03 01:58
Hello @Pamyux3 

To make it work you have to add this in the unit's init:

`
[this] call HG_fnc_aiUnitSetup
`

Thanks for using SimpleShops.

**Comment by Pamyux3** [comment] 2022-04-03 06:57
Thank you for such a fast answer. I will try it as soon as possible.

**Comment by Ppgtjmad** [comment] 2022-04-08 19:48
I guess the problem is solved, closing this ticket.

**Closed by Ppgtjmad** 2022-04-08 19:48 UTC
